version: "3.9"

services:
  ann:
    restart: always
    image: ghcr.io/openfoodfacts/robotoff-ann:${TAG}
    ports:
      - ${ANN_EXPOSE:-5501}:5501
    volumes:
      - ${ANN_DATA_MOUNT_POINT:-./ann_data}:/opt/ann/data
    environment:
      - SENTRY_DSN
