name: ANN Data Deployment CI

on:
  push:
    branches:
      - deploy-efficientnet-*
    tags: 
      - v*.*.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - ${{ startsWith(github.ref, 'refs/tags/v') && 'robotoff-ann-org' || 'robotoff-ann-net' }}
    environment: ${{ matrix.env }}
    concurrency: ${{ matrix.env }}-data
    steps:
    - name: Download efficientnet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.USERNAME }}
        proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
        timeout: 30m
        script_stop: false
        script: |
          cd ${{ matrix.env }}
          make init-data
