name: Publish Docker Hub image and PyPI package
on:
  push:
    tags:
      - v*.*.*

jobs:
  push_to_registry:
    name: Push robotoff Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: openfoodfacts/robotoff-ann
          tag_with_ref: true
          add_git_labels: true
